name: Build Document
on: [push, pull_request, workflow_dispatch]
jobs:
    build_document:
        name: Build Document
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Build
                run: |
                    sudo apt update &&
                    sudo apt install -y asciidoctor ruby-asciidoctor-pdf pandoc &&
                    asciidoctor-pdf docs/VMC-Requirements.adoc &&
                    /bin/bash -c "asciidoctor --backend docbook --out-file - docs/VMC-Requirements.adoc | pandoc --from docbook --to docx --output docs/VMC-Requirements.docx"
            -   uses: actions/upload-artifact@v3
                with:
                    path: |
                        docs/VMC-Requirements.pdf
                        docs/VMC-Requirements.docx
                    if-no-files-found: 'error'
