name: Build Document
on: [push, pull_request, workflow_dispatch]
jobs:
    build_document:
        name: Build Document
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Build
                run: |
                    sudo apt update &&
                    sudo apt install -y asciidoctor ruby-asciidoctor-pdf &&
                    asciidoctor-pdf docs/VMC-Requirements.adoc
            -   uses: actions/upload-artifact@v3
                with:
                    name: VMC-Requirements.pdf
                    path: |
                        docs/VMC-Requirements.pdf
                    if-no-files-found: 'error'
